version: 19.03.0

services:
  db:
    image: mysql:latest
    container_name: mydb1
    networks:
    - lwnet
    volumes:
    - /data:/var/lib/mysql
    environment:
    - MYSQL_ROOT_PASSWORD=redhat
    - MYSQL_DATABASE=blogdb
    - MYSQL_USER=vimal
    - MYSQL_PASSWORD=redhit

  wp:
   depends_on:
   - db
   image: wordpress:latest
   container_name: mywp1
   networks:
   - lwnet
   ports:
   - 8080:80
   environment:
   - WORDPRESS_DB_HOST=mydb1
